kornelski/cargo-deb

src/main.rs, src/manifest.rs
Hello! 
please consider the following PR :)
Currently cargo-deb only packages assets in the release profile. e.g. /target/release/...
My PR enables to create packages from debug or custom profiles. e.g. /target/my_custom_profile
- ive added a `--profile` application argument option. to keep terminology consistent  with cargo
- if no `--profile` argument is given, default to `release`
You could work around this by creating an `[package.metadata.deb.variants.$name]` for each permutation, manually writing out the correct path to the assets. but in projects with `x profiles` times `y projects` this is not nice..
=> Add support for cargo profiles.

src/control.rs, src/lib.rs, src/main.rs, src/manifest.rs
Hello, thank you for processing my recent PR's!
so my previous PR only supports `--profile` with `--no-build`. this PR enables to actually build the profile passed on to the CLI options.
e.g. you can do for instance 'cargo deb -p my_package --manifest-path applications/my_app/Cargo.toml --profile RelWithDebInfo --no-strip'
The other guy from the issue list will probably be happy to get it as well.
PS; you probably already know, but there is quite some technical debt in the build flags support.. i shouldnt really need to explicitly pass `--no-strip` if my cargo profile states that i want debug symbols
=> Enable building with cargo profiles

src/dependencies.rs, src/manifest.rs
Assuming sysroots are all stored in `/usr`, use the target to generate a
library search path and append the appropriate args.
This works for me (also on Ubuntu 20.04), but may not fix #5. I don't see
the extra `libgcc1-arm64-cross` mentioned in that issue, instead I have 
`libgcc-s1-arm64-cross` which is filtered by post-processing.
=> Use target to generate a library path for dpkg_shlibdeps

src/main.rs, src/manifest.rs
Adding an option override revision instead of whole version at command line
Corresponding to old repo issue:
https://github.com/mmstick/cargo-deb/issues/196
=> Adding deb-revision option to specify alternate revision for package

README.md
As discussed in issue #27, suggest a container/vm for targeting old releases w/ library dependencies.
=> Suggest container/vm for cross-compiling to old releases.

src/compress.rs, src/config.rs, src/control.rs, src/data.rs, src/dependencies.rs, src/dh_installsystemd.rs, src/dh_lib.rs, src/lib.rs, src/main.rs, src/manifest.rs, src/util.rs
Hello, thank you for this useful crate !
Currently, when specifying a `triggers-file` that doesn't exist, `cargo-deb` will silently ignore it. The first commit of this PR adds a check and raise an error if the file can't be found. The second commit fixes the path of the file to be relative to the manifest directory, allowing `triggers-file` to be included when building outside of the manifest directory with the `--package` or `--manifest-path` options. I also fixed some `clippy` warnings.
=> look for triggers-file relative to manifest dir

src/data.rs, src/manifest.rs
Fixes https://github.com/kornelski/cargo-deb/issues/44
Edit: the warning was because of my library side issue. This should fix the issue #44.
Edit: 
This causes warning on running dpkg-shlibdeps.
```
warning: dpkg-shlibdeps (/home/naoaki/src/cskk/deb_assets/libcskk.so.0): dpkg-shlibdeps: error: cannot read /home/naoaki/src/cskk/deb_assets/libcskk.so.0: No such file or directory
(no auto deps for /home/naoaki/src/cskk/deb_assets/libcskk.so.0)
warning: dpkg-shlibdeps (/home/naoaki/src/cskk/deb_assets/libcskk.so): dpkg-shlibdeps: error: cannot read /home/naoaki/src/cskk/deb_assets/libcskk.so: No such file or directory
(no auto deps for /home/naoaki/src/cskk/deb_assets/libcskk.so)
```
Edit2: Fixed the above warnings.
=> Fix symbolic link couldn't be included in deb file Fix Issue#44

Cargo.lock, Cargo.toml, src/lib.rs, src/main.rs
We have a use case for using zigbuild alongside cargo-deb to lock the glibc version. This integration appears to be almost seamless, as zigbuild supports most (maybe all?) of `cargo-build`'s build flags.
By keeping `cargo-build` the default, we don't run the risk of having to include dependency management for the `cargo-zigbuild` binary, nor do we have to worry about current behavior changing in regards to the target triplet (`zigbuild` adds the glibc version to the end of the triplet such that it would look like: `aarch64-unknown-linux-gnu-2.17`, and thus the ABI would be `linux-gnu-2.17`. This won't break any existing mapping for the debian architectures, only custom behavior built upon the fallback case.)
=> Add cargo-build override (support `zigbuild`)

src/manifest.rs
Need to call `complete_from_path` after `inherit_workspace` otherwise inherited fields are accessed before they have been defined.
Bug is reproducible by inheriting `edition` or `readme` from the workspace. For `edition` you need either a `lib.rs` or `main.rs` (or both) in the package (empty files are sufficient).
I have a minimal test for `cargo_toml`, but it seems to be expected behavior based on the function descriptions.
Triggered by `edition` with `lib.rs`:
https://gitlab.com/crates.rs/cargo_toml/-/blob/3c9c20e07638dba7f7ba462f6d5f9247146cd93b/src/cargo_toml.rs#L366
Triggered by `edition` with `main.rs`:
https://gitlab.com/crates.rs/cargo_toml/-/blob/3c9c20e07638dba7f7ba462f6d5f9247146cd93b/src/cargo_toml.rs#L388
Triggered by `readme`: …
=> Fix workspace inheritance bug

src/pathbytes.rs
Fix a type error on non-`unix` targets.
=> pathbytes: fix <Path as AsUnixPathBytes>::to_bytes on non-unix targets

src/manifest.rs, systemd.md
A continuation of https://github.com/kornelski/cargo-deb/pull/65
* Adding `enum` for backword compatibility where a user can specify a single file as previously allowed or multiple systemd unit files.
* Adding doc example to illustrate usage for multiple systemd unit files.
=> Adding docs and backward compat to multi systemd unit files

.github/workflows/cargo.yml
See https://github.com/actions-rs/toolchain/issues/219 and https://github.com/actions-rs/toolchain/issues/216
=> Migrate away from abandoned `actions-rs/*` GitHub Actions

.github/workflows/cargo.yml
The `dtolnay/rust-toolchain` action automagically enables the sparse crates.io protocol, so it's not necessary to do so manually.
=> Drop redundant `CARGO_REGISTRIES_CRATES_IO_PROTOCOL` env in CI workflow

src/lib.rs, src/manifest.rs, tests/command.rs
Previously cargo-deb attempted to add the files with debug symbols by referencing the stripped executable path.  The debug symbols do not live alongside the stripped executables so this always failed.
Now cargo-deb uses the original executable paths to determine the location of the debug symbols.
(There's probably a better way to do this, but I'm not skilled enough to figure out how to use collect() with the parallel iterator.)
=> Fix --separate-debug-symbols

src/config.rs, src/manifest.rs
Split into two commits:
* ef61969d8b0303f479d87f47325ec735f074e11d is just the fix for #84   
* 1f7f1fb372f6135817c2696d24432580c3d9e4d4 adds a code path that looks for the config file in `$CARGO_HOME`
I left the "old" home directory check in as a fallback, but I can also revert the second commit altogether if you prefer.
=> Fix search path for `cargo` configuration

Cargo.toml
IIUC the async machinery is not used in any way, so it's better to disable it to prune the dev dependency tree.
=> Disable the async-timeout feature for rstest

README.md, src/compress.rs, src/main.rs, tests/command.rs
I aligned the options with dpkg-deb (<https://manpages.ubuntu.com/manpages/kinetic/en/man1/dpkg-deb.1.html>) but I'm of course happy to change the names.
Closes: #96 
TODO:
=> Implement command-line options for compression format selection

src/manifest.rs, tests/command.rs
Bringing the 2 commits we discussed today:
- including a default revision in the manifest version string if no revision is specified
- returning the manifest version string as a Cow<str> to avoid copying a string uselessly
=> Defaultrevision

README.md
Replaced https://packages.debian.org/stretch/
with https://packages.debian.org/bookworm/
=> Updated link of application category

Cargo.lock, Cargo.toml, src/compress.rs
Given that `std::thread::available_parallelism` was stabilized on Rust 1.59 and the MSRV of this crate is 1.63, we can safely use this new standard library function, whose behavior is equivalent to `num_cpus::get`, but better documented and likely to receive more maintenance and care.
=> Drop dependency on `num_cpus` for `std::thread::available_parallelism`

src/debarchive.rs, tests/command.rs
I added some test code to verify the ar format used is as expected. I also tested opening the produced .deb in file-roller, which now works!
Fixes: #126
=> Switch ar file type/mode to 100644 as used by dpkg

README.md, src/control.rs, src/main.rs, src/manifest.rs
Previously this was documented to be configurable from the [[package.metadata.deb]] table but was in fact ignored and only the command line parameter was used.
This honors the value from Cargo.toml if no command line option is specified. The existing --separate-debug-symbols option can still be used to enable the inclusion of a separate debug symbol file. A new --no-separate-debug-symbols option can be used to suppress it, overriding a possible Cargo.toml value that would have led to its inclusion.
This should fix #129
I tested all combinations in a Debian bookworm container but there is no reason to believe that the behavior should differ on other Debian versions since this change is completely limited to the internal combination of the boolean values and does not touch the actual …
=> Use separate-debug-symbols value from Cargo.toml

src/lib.rs
=> Allow --cargo-deb to contain multiple arguments

CHANGELOG.md, src/config.rs
Remove `Vcs-*` from the control file as it only exists in the source control file not the binary control file.
=> Don't add Vcs-* to the binary control file.

src/assets.rs
The function returned the inverse of what its name suggests. That is, it returned false for assets that are marked `SamePackage`. This causes cargo-deb to unnecessarily pass `--workspace` to cargo build, which affects feature resolution even if only a single target is built.
=> Fix Asset::is_same_package comparison

src/assets.rs
`folder/**/*` patterns should not flatten directory structure. This is a regression introduced in #168.
Ref #41
=> Fix glob in asset path flattening structure

README.md
Removed duplicate entry for 'conf-files' in README.
=> Fix duplicate 'conf-files' entry in README
